#image: java:8-jdk
#Runs on a centos-8,java-openjdk-11 machine

stages:
  - build
  - publish

variables:
  GIT_DEPTH: 0 # clone all

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - chmod +x ./gradlew

build:
  stage: build
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - .gradle/
      - build/
    policy: pull
  script:
    - ./gradlew build
  artifacts:
    paths:
      - 'build/libs/*.jar'
    expire_in: 1 week
  except:
    - tags

publish:
  stage: publish
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - .gradle/
      - build/
    policy: pull
  script:
    - './gradlew curseforge'
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^\d\.\d{1,3}(?:\.(?:\d{1,3}|x))?$/'
      when: always
    - when: never
