modLoader="javafml"
loaderVersion="[34,)"
license="GNU GPLv3"
issueTrackerURL="https://github.com/percivalalb/Trapcraft/issues"
displayURL="https://minecraft.curseforge.com/projects/trapcraft/"
logoFile="tc_logo.png"

[[mods]] #mandatory
    modId="trapcraft"
    version="${version}"
    updateJSONURL="https://raw.githubusercontent.com/percivalalb/Trapcraft/1.16.x/version.json"
    displayName="Trapcraft"
    credits="Authored By ProPercivalalb"
    authors="ProPercivalalb, Stewiecraft"
    description='''
    Addeds new blocks to create traps with, (Fan, Bear Trap, Igniter, Magnetic Chest and Grass Coverings), also a dummy. Plus upgrade your traps with special upgrades!
    '''

[[dependencies.jei]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="${forge_version}" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.jei]]
    modId="minecraft" #mandatory
    mandatory=true #mandatory
    versionRange="${mc_version}" #mandatory
    ordering="NONE"
    side="BOTH"
